# -*- coding: utf-8 -*-
{
    'name': 'Crossnexion - Reportes Contables Paraguay',
    'summary': 'Este modulo genera los reportes contables del Paraguay',
    'author': 'Crossnexion EAS',
    'website': 'www.crossnexion.com',
    'license': 'OPL-1',
    'category': 'Uncategorized',
    'version': '25.5.7',
    'depends': [
        'base',
        'account',
        'l10n_py',
        'electronic_invoice_cross_py',
    ],
    'data': [
        'data/report_paperformat.xml',
        'data/res.company.legal.personality.csv',
        'data/res.company.type.obligations.csv',
        'data/ir_sequence.xml',
        'data/account.move.receipt.type.csv',
        'data/account.move.receipt.code.csv',
        'data/account.move.form.type.csv',
        'data/account.move.selection.state.csv',
        'data/account.move.reasons.inclusion.csv',
        'security/ir.model.access.csv',
        'views/res_company.xml',
        'views/res_company_legal_personality.xml',
        'views/res_company_type_obligations.xml',
        'views/account_move_receipt_code.xml',
        'views/account_move.xml',
        'views/account_move_form_type.xml',
        'views/account_move_reasons_inclusion.xml',
        'views/account_payment_term.xml',
        'wizard/account_books_report_wizard.xml',
        'wizard/rg90_report_wizard.xml',
        'wizard/account_books_cancel_wizard.xml',
        'wizard/account_move_getinfo_wizard.xml',
        'wizard/cross_from_to_wizard.xml',
        'reports/account_books_report.xml',
        'reports/financial_report_collectpay.xml',
        'reports/partner_financial_report.xml',
    ],
}
